[tool.poetry]
name = "chat-client"
version = "0.1.0"
description = "chat client for llm-server"
authors = ["iabhyuday <abhyuday964808@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.43.2"
redis = "^5.2.1"
llama-index = "^0.12.23"
llama-cloud-services = "^0.6.5"
llama-index-vector-stores-chroma = "^0.4.1"
google-generativeai = "^0.8.4"
llama-index-embeddings-huggingface-api = "^0.3.0"
pymupdf = "^1.25.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
