version: "3"

services:
  llm-document-retriever:
    image: siemens/llm-document-retriever:1.0
    build:
      target: development
    volumes:
      - "./siemens/app/:/app"
    command: tail -F sleep infinity
